### ISSUE TITLE
Missing partition key on header

### ISSUE THREAD

**Issue by wikes82** [Azure/Azure.Android#75]
## Bug Information
when calling AzureData.createDocument() to collection with partition key, it produce error : The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.
REST request header missing x-ms-documentdb-partitionkey 

### Steps to Reproduce
call AzureData.createDocument() to collection with partition key.

**Comment by NateRickard** [comment]
It looks like this change in the portal:

<img width="388" alt="screenshot 2019-02-05 16 04 14" src="https://user-images.githubusercontent.com/2753695/52304826-93380780-2961-11e9-8790-5ace62f6a394.png">

...is causing all collections created via the portal to require a partition key.  Currently this SK has no method of passing a partition key in the header, leading to the error.

This SDK will be updated to allow for the partition key.  In the meantime, a workaround is to create the collection programmatically via the SDK, which does not require a partition key to be set.

**Comment by SogoGolf** [comment]
thanks for confirming this @NateRickard looking forward to the update

**Comment by NateRickard** [comment]
@SogoGolf should be fixed in PR #86/v0.2.0

**Comment by SogoGolf** [comment]
hi @NateRickard just tested this and I'm still seeing same error. i checked i had updated to 0.2.0 perhaps i missed something else. here's the details:

the database ```test``` and collection ```testcollection``` were created in the portal UI.

![image](https://user-images.githubusercontent.com/19580787/53211056-0ba60480-3694-11e9-952e-12a016c47b03.png)

![image](https://user-images.githubusercontent.com/19580787/53210995-d1d4fe00-3693-11e9-99a3-18840d84a117.png)

```    
implementation 'com.azure.android:azuredata:0.2.0'
```
update worked fine/build ok.

doc class:
```
class ClubDocument(id: String? = null) : Document(id) {
    var name: String = ""
    var type: String = ""
}
```

test code block:
```
val document = ClubDocument()
document.name = "NEW CLUB ${(0..100).random()}"
document.type = "abc"

AzureData.createDocument (document, "testcollection", "test") {
    // created document = it.resource
    if (it.response != null && it.response?.isSuccessful!!) {
        lastAddedId = it.resource?.id!!
        runOnUiThread {
            textView.text = "success creating a new club. ${it.jsonData}"
        }
    } else {
        Log.i("AZURE", "ERROR: create document failed. ${it.jsonData}")
        runOnUiThread {
            textView.text = "ERROR: ${it.jsonData}"
        }
    }
}
```

error message:
```
create document failed. {"code":"BadRequest","message":"Message: {\"Errors\":[\"The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.\"]}
```

**Comment by NateRickard** [comment]
@SogoGolf mark the property you're using as the partition key with the `@PartitionKey` annotation, e.g.:

```
@PartitionKey
    var testKey = "MyPartitionKey"
```

Docs are lagging behind as we iterate on this, but you can [look at the tests](https://github.com/Azure/Azure.Android/blob/master/azuredata/src/androidTest/java/com/azure/data/integration/CustomDocumentPartitionedTests.kt) which should give you some insight.

**Comment by radoye** [comment]
I can't seem to find an example for Java. I tried something like the snipped below, but it's failing. Any hints/pointers? Thanks!

```java
    static class SampleDocument extends Document {
        String guid;
        @PartitionKey // <== fails here with "@PartitionKey not applicable to field"
        String guid_date;
        JSONObject payload;

      SampleDocument(...) {}
}
```

**Comment by NateRickard** [comment]
@radoye thanks for the feedback.  I've updated the attribute to work on fields as well.  Let me know if this fixes the issue for you.  Released in v0.2.5.

**Comment by radoye** [comment]
@NateRickard thanks for the fix! I can confirm that it works in 0.2.5.
